apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: local-operator-group-hhvzv
  namespace: openshift-local-storage
spec:
  targetNamespaces:
    - openshift-local-storage
  upgradeStrategy: Default

