apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    cluster.ocs.openshift.io/local-devices: "true"
    uninstall.ocs.openshift.io/cleanup-policy: delete
    uninstall.ocs.openshift.io/mode: graceful
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  encryption:
    enable: true
  flexibleScaling: true
  monDataDirHostPath: /var/lib/rook
  resources:
    mds:
      limits:
        cpu: "3"
        memory: 8Gi
      requests:
        cpu: "1"
        memory: 8Gi
    rgw:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 4Gi
  storageDeviceSets:
  - count: 3
    dataPVCTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "1"
        storageClassName: storage-localblock-sc
        volumeMode: Block
    name: ocs-deviceset-storage-localblock-sc
    replica: 1
    resources:
      limits:
        cpu: "2"
        memory: 5Gi
      requests:
        cpu: "1"
        memory: 5Gi
  version: 4.9.0
